# Top 30 goleadores activos de selecciones clasificadas al Mundial 2026
# Ordenados por goles en carrera internacional (verificado a mayo 2025)

TOP_SCORERS = [
    {"name": "Cristiano Ronaldo",   "country": "🇵🇹 Portugal",            "goals": 143},
    {"name": "Lionel Messi",        "country": "🇦🇷 Argentina",            "goals": 116},
    {"name": "Romelu Lukaku",       "country": "🇧🇪 Bélgica",              "goals": 89},
    {"name": "Neymar",              "country": "🇧🇷 Brasil",               "goals": 79},
    {"name": "Harry Kane",          "country": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra",          "goals": 78},
    {"name": "Edin Džeko",          "country": "🇧🇦 Bosnia y Herz.",       "goals": 73},
    {"name": "Mohamed Salah",       "country": "🇪🇬 Egipto",               "goals": 67},
    {"name": "Kylian Mbappé",       "country": "🇫🇷 Francia",              "goals": 56},
    {"name": "Erling Haaland",      "country": "🇳🇴 Noruega",              "goals": 55},
    {"name": "Memphis Depay",       "country": "🇳🇱 Países Bajos",         "goals": 55},
    {"name": "Son Heung-min",       "country": "🇰🇷 Corea del Sur",        "goals": 54},
    {"name": "Sadio Mané",          "country": "🇸🇳 Senegal",              "goals": 53},
    {"name": "Enner Valencia",      "country": "🇪🇨 Ecuador",              "goals": 49},
    {"name": "Antoine Griezmann",   "country": "🇫🇷 Francia",              "goals": 44},
    {"name": "Raúl Jiménez",        "country": "🇲🇽 México",               "goals": 44},
    {"name": "Almoez Ali",          "country": "🇶🇦 Qatar",                "goals": 42},
    {"name": "Sardar Azmoun",       "country": "🇮🇷 Irán",                 "goals": 41},
    {"name": "Mehdi Taremi",        "country": "🇮🇷 Irán",                 "goals": 38},
    {"name": "Andrej Kramarić",     "country": "🇭🇷 Croacia",              "goals": 36},
    {"name": "Lautaro Martínez",    "country": "🇦🇷 Argentina",            "goals": 32},
    {"name": "Jonathan David",      "country": "🇨🇦 Canadá",               "goals": 31},
    {"name": "Cyle Larin",          "country": "🇨🇦 Canadá",               "goals": 31},
    {"name": "Darwin Núñez",        "country": "🇺🇾 Uruguay",              "goals": 26},
    {"name": "Julián Álvarez",      "country": "🇦🇷 Argentina",            "goals": 26},
    {"name": "Hirving Lozano",      "country": "🇲🇽 México",               "goals": 26},
    {"name": "Hakim Ziyech",        "country": "🇲🇦 Marruecos",            "goals": 23},
    {"name": "Bukayo Saka",         "country": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra",          "goals": 22},
    {"name": "Vinícius Júnior",     "country": "🇧🇷 Brasil",               "goals": 21},
    {"name": "Youssef En-Nesyri",   "country": "🇲🇦 Marruecos",            "goals": 21},
    {"name": "Gabriel Jesus",       "country": "🇧🇷 Brasil",               "goals": 19},
]
